name: test
channels:
    - conda-forge
    - chilipp
dependencies:
    - python=2.7
    - scipy<1.3   # for statsmodels compatibility
    - matplotlib
    - dask
    - pip
    - xarray
    - numpy
    - netcdf4
    - seaborn
    - bottleneck
    - statsmodels
    - docrep
    - model-organization
    - f90nml
    - cartopy
    - sqlalchemy
    - psycopg2
    - psyplot
    - psy-simple
    - psy-reg
