name: gwgen
channels:
    - conda-forge
dependencies:
    - psyplot
    - dask
    - xarray
    - netCDF4
    - cartopy
    - seaborn
    - bottleneck
    - scipy<1.3   # for statsmodels compatibility
    - pip:
        - sqlalchemy
        - model-organization
